name: Throne Underlying Builder

on:
  workflow_dispatch:
  push:
    branches: [ main , "releases/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CI_TOKEN }}
        submodules: true
        

    - name: Notify Throne Rebuild
      run: |
            curl -XPOST -u "${{ secrets.CI_TOKEN }}" -H "Accept:application/vnd.github" -H "Content-Type:application/json" https://api.github.com/repos/Yuzu-swap/league-of-thrones-front/actions/workflows/app.yml/dispatches --data "{\"ref\": \"${GITHUB_REF##*/}\" }"

    - name: Notify Throne backend Rebuild
      run: |
            curl -XPOST -u "${{ secrets.CI_TOKEN }}" -H "Accept:application/vnd.github" -H "Content-Type:application/json" https://api.github.com/repos/Yuzu-swap/league-of-thrones-backend/actions/workflows/app.yml/dispatches --data "{\"ref\": \"${GITHUB_REF##*/}\" }"